import {memo,useEffect,useMemo,useState,type CSSProperties} from 'react';
import {useStore} from './store';
import type{AppConfig,Encoder,FitMode,LatencyPreference,MediaInfo,QualityStrategy,SceneType,SessionEvent,StreamMode,StreamState,StreamStats}from'../shared/types';
const fmt=(n:number)=>{const h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=Math.floor(n%60);return`${h?String(h).padStart(2,'0')+':':''}${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`};
const mb=(n:number)=>(n/1024/1024).toFixed(1);
const speedNum=(s:string)=>parseFloat((s||'0').replace('x',''))||0;
function fileUrl(p:string){return encodeURI(`file:///${p.replace(/\\/g,'/')}`)}
function Badge({state,label}:{state:StreamState|'ready';label?:string}){return <span className={`badge b-${state}`}><i/>{label||String(state).toUpperCase()}</span>}
const Toggle=memo(function Toggle({title,sub,on,set,disabled=false}:{title:string;sub?:string;on:boolean;set:(x:boolean)=>void;disabled?:boolean}){return <label className={`toggleRow ${disabled?'disabled':''}`}><span><b>{title}</b>{sub&&<small>{sub}</small>}</span><span className={`switch ${on?'on':''}`}><input type="checkbox" checked={on} disabled={disabled} onChange={e=>set(e.target.checked)}/><i/></span></label>});
function Thumb({media}:{media:MediaInfo}){const[src,setSrc]=useState('');useEffect(()=>{let ok=true;window.arsal.thumbnail(media.path).then(p=>{if(ok&&p)setSrc(fileUrl(p))});return()=>{ok=false}},[media.path]);return <div className="thumb">{src?<img src={src}/>:<span>▶</span>}</div>}
function Preview({kind,index,setIndex,stats}:{kind:'horizontal'|'vertical';index:number;setIndex:(n:number)=>void;stats:StreamStats}){const cfg=useStore(s=>s.cfg),playlist=useStore(s=>s.playlist),setOut=useStore(s=>s.setOut),o=cfg[kind],m=playlist[index],inactive=(cfg.mode==='horizontal'&&kind==='vertical')||(cfg.mode==='vertical'&&kind==='horizontal');const fit:CSSProperties['objectFit']=o.fit==='fit'?'contain':o.fit==='stretch'?'fill':o.fit==='original'?'none':'cover';const next=()=>{if(!playlist.length)return;if(index<playlist.length-1)setIndex(index+1);else if(cfg.loop)setIndex(0)};return <article className={`previewCard ${inactive?'inactive':''}`}><header><span><em className={`ratio ${kind}`}>{kind==='horizontal'?'16:9':'9:16'}</em><b>{kind==='horizontal'?'Horizontal':'Vertical'} Output</b><small>{stats.effectiveWidth||o.width}×{stats.effectiveHeight||o.height} · {stats.effectiveFps||o.fps}fps</small></span><Badge state={inactive?'offline':stats.state} label={inactive?'DISABLED':undefined}/></header><div className="canvas" style={{aspectRatio:kind==='horizontal'?'16/9':'9/16'}}>{m?<video key={`${m.path}-${index}`} src={fileUrl(m.path)} controls muted preload={cfg.previewQuality==='low'?'none':'metadata'} loop={playlist.length===1&&cfg.loop} onEnded={next} style={{objectFit:fit,objectPosition:`${o.cropX}% ${o.cropY}%`,transform:`scale(${o.zoom/100})`}}/>:<div className="emptyCanvas"><span>＋</span><b>Add media to preview</b><small>Playlist video appears here before you go live.</small></div>}{inactive&&<div className="disabledCanvas">Disabled in current Stream Mode</div>}</div><footer><select value={o.fit} onChange={e=>setOut(kind,{fit:e.target.value as FitMode})}><option value="fit">Fit / contain</option><option value="fill">Fill / crop</option><option value="stretch">Stretch</option><option value="original">Original centered</option></select><span>{m?`${index+1}/${playlist.length} · ${m.name}`:'No source'}</span></footer></article>}
function KeyField({kind,stats}:{kind:'horizontal'|'vertical';stats:StreamStats}){const o=useStore(s=>s.cfg[kind]),setOut=useStore(s=>s.setOut);const[show,setShow]=useState(false);return <div className="destCard"><div className="destHead"><span><i className={`route ${kind}`}/><b>{kind==='horizontal'?'Primary / Horizontal':'Vertical / Second'}</b></span><Badge state={o.key?(stats.state==='offline'?'ready':stats.state):'offline'} label={o.key?(stats.state==='offline'?'CONFIGURED':undefined):'KEY REQUIRED'}/></div><label><span>Server URL</span><input value={o.server} disabled={stats.state!=='offline'} onChange={e=>setOut(kind,{server:e.target.value})}/></label><label><span>Stream key</span><div className="keyrow"><input type={show?'text':'password'} value={o.key} autoComplete="off" placeholder="Paste stream key" disabled={stats.state!=='offline'} onChange={e=>setOut(kind,{key:e.target.value})}/><button onClick={()=>setShow(!show)}>{show?'Hide':'Show'}</button><button disabled={stats.state!=='offline'} onClick={async()=>{try{const k=(await navigator.clipboard.readText()).trim();if(k)setOut(kind,{key:k})}catch{}}}>Paste</button></div></label><div className="destState"><span>{stats.state==='streaming'?'✓ Real ingest packets flowing':'Awaiting live ingest confirmation'}</span>{stats.profileLabel&&<span>{stats.profileLabel}</span>}</div>{stats.lastError&&<div className="inlineError">{stats.lastError}</div>}</div>}
function StreamStat({title,on,st,playlist}:{title:string;on:boolean;st:StreamStats;playlist:MediaInfo[]}){const item=playlist[st.playlistIndex||0],spd=speedNum(st.speed);return <div className={`statCard ${on?'':'muted'}`}><div className="statHead"><b>{title}</b><span className={`healthPill hp-${st.health||'idle'}`}>{on?(st.health||'idle').toUpperCase():'DISABLED'}</span></div><div className="metricGrid"><Metric l="FPS" v={on&&st.fps?st.fps.toFixed(1):'—'}/><Metric l="Bitrate" v={on&&st.bitrateKbps?`${Math.round(st.bitrateKbps)}k`:'—'}/><Metric l="Speed" v={on?st.speed||'—':'—'} cls={spd&&spd<.95?'bad':''}/><Metric l="Reconnects" v={on?String(st.reconnects):'—'}/><Metric l="Profile" v={on?(st.profileLabel||'—'):'—'}/><Metric l="Dropped" v={on?String(st.droppedFrames||0):'—'}/></div><div className="playing"><small>NOW PLAYING</small><b>{on&&item?`${(st.playlistIndex||0)+1}/${playlist.length} · ${item.name}`:'—'}</b></div>{st.lastWarning&&<div className="warningLine">⚠ {st.lastWarning}</div>}{st.lastError&&<div className="errorLine">{st.lastError}</div>}</div>}
function Metric({l,v,cls=''}:{l:string;v:string;cls?:string}){return <div className={`metric ${cls}`}><small>{l}</small><b>{v}</b></div>}
function Section({eyebrow,title,children,className=''}:{eyebrow:string;title:string;children:any;className?:string}){return <section className={`panel ${className}`}><div className="panelTitle"><span><small>{eyebrow}</small><h2>{title}</h2></span></div>{children}</section>}
function Field({label,children,hint}:{label:string;children:any;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
function DayPicker({cfg,setCfg}:{cfg:AppConfig;setCfg:(x:Partial<AppConfig>)=>void}){const names=['S','M','T','W','T','F','S'];return <div className="dayPicker">{names.map((n,i)=><button key={i} className={cfg.scheduler.weekdays.includes(i)?'on':''} onClick={()=>{const x=cfg.scheduler.weekdays.includes(i)?cfg.scheduler.weekdays.filter(d=>d!==i):[...cfg.scheduler.weekdays,i];setCfg({scheduler:{...cfg.scheduler,weekdays:x}})}}>{n}</button>)}</div>}
export default function App(){
 const cfg=useStore(s=>s.cfg),playlist=useStore(s=>s.playlist),h=useStore(s=>s.h),v=useStore(s=>s.v),setCfg=useStore(s=>s.setCfg),addPlaylist=useStore(s=>s.addPlaylist),removeMedia=useStore(s=>s.removeMedia),reorderMedia=useStore(s=>s.reorderMedia),clearPlaylist=useStore(s=>s.clearPlaylist),setOut=useStore(s=>s.setOut),setStat=useStore(s=>s.setStat);
 const[ready,setReady]=useState<any>(null),[sessionActive,setSessionActive]=useState(false),[message,setMessage]=useState('Add media, paste your YouTube key, then press Auto Optimize.'),[previewIndex,setPreviewIndex]=useState(0),[tab,setTab]=useState<'health'|'tools'|'events'>('health'),[scene,setScene]=useState<SceneType>('video'),[events,setEvents]=useState<SessionEvent[]>([]),[network,setNetwork]=useState<any>(null),[system,setSystem]=useState<any>(null),[drag,setDrag]=useState<number|null>(null),[profiles,setProfiles]=useState<any[]>(()=>{try{return JSON.parse(localStorage.getItem('arsalProfiles')||'[]')}catch{return[]}}),[profileName,setProfileName]=useState(''),[scheduleGuard,setScheduleGuard]=useState('');
 const addEvent=(level:SessionEvent['level'],msg:string)=>setEvents(x=>[...x.slice(-149),{time:Date.now(),level,message:msg}]);
 useEffect(()=>{window.arsal.loadConfig().then(c=>useStore.setState({cfg:c}));window.arsal.systemInfo().then(setSystem);const a=window.arsal.onStats(({key,stats})=>{setStat(key,stats);if(stats.currentScene)setScene(stats.currentScene)}),b=window.arsal.onEvent(e=>{setEvents(x=>[...x.slice(-149),e])});return()=>{a();b()}},[setStat]);
 useEffect(()=>{const t=setTimeout(()=>window.arsal.saveConfig(cfg),600);return()=>clearTimeout(t)},[cfg]);
 useEffect(()=>{if(previewIndex>=playlist.length)setPreviewIndex(Math.max(0,playlist.length-1))},[playlist.length,previewIndex]);
 const hOn=cfg.mode!=='vertical',vOn=cfg.mode!=='horizontal',required=[...(hOn?[h]:[]),...(vOn?[v]:[])],live=required.length>0&&required.every(s=>s.state==='streaming'),connecting=sessionActive&&!live&&required.some(s=>['connecting','reconnecting','preparing'].includes(s.state)),critical=required.some(s=>s.health==='critical'||s.state==='error'),poor=required.some(s=>s.health==='poor'||speedNum(s.speed)<.95&&s.state==='streaming'),health=!sessionActive?(ready?.ok?'READY':'IDLE'):critical?'CRITICAL':poor?'POOR':connecting?'CONNECTING':live?'HEALTHY':'ACTIVE',keysReady=(!hOn||!!cfg.horizontal.key)&&(!vOn||!!cfg.vertical.key),configuredKbps=(hOn?cfg.horizontal.bitrateKbps:0)+(vOn?cfg.vertical.bitrateKbps:0)+(cfg.audioEnabled?(cfg.mode==='dual'?256:128):0);
 async function addVideos(){const items=await window.arsal.openVideos();if(items.length){addPlaylist(items);setReady(null);setMessage(`${items.length} video${items.length>1?'s':''} added.`);addEvent('success',`${items.length} media item(s) added to playlist.`)}}
 async function preflight(){const r=await window.arsal.preflight({playlist,cfg});setReady(r);setTab('health');setMessage(r.ok?'Pre-flight passed. LIVE will only appear after real ingest starts.':'Pre-flight found blocking issues.');return r}
 async function startStream(auto=false){const r=await preflight();if(!r.ok)return;if(!auto&&!confirm(`Start live stream?\n\n${playlist.length} video(s) · ${cfg.mode}\n${(configuredKbps/1000).toFixed(1)} Mbps configured\nAdaptive Network: ${cfg.adaptiveNetwork?'ON':'OFF'}`))return;const x=await window.arsal.start({playlist,cfg});if(x.ok){setSessionActive(true);setScene('video');setMessage(x.fallbackFrom?`${x.fallbackFrom.toUpperCase()} unavailable — switched to CPU. Connecting…`:`${x.encoder.toUpperCase()} validated. Connecting to YouTube…`);addEvent('info','Streaming session started.')}else setMessage(x.error)}
 async function stopStream(){if(!confirm('Stop live stream?'))return;await window.arsal.stop();setSessionActive(false);setScene('video');setMessage('Stream stopped safely.');addEvent('info','Streaming session stopped.')}
 async function switchScene(s:SceneType){if(!sessionActive)return;await window.arsal.switchScene(s);setScene(s);addEvent('info',`Scene requested: ${s}.`)}
 async function fixStream(){if(sessionActive){await window.arsal.fixStream();setMessage('Fix My Stream applied a safer runtime profile.');addEvent('warning','Fix My Stream applied automatic recovery.')}else{applySafeMode();setMessage('Safe settings applied for the next stream.')}}
 function applyPreset(level:number){const hs=[{width:1920,height:1080,fps:30,bitrateKbps:10000},{width:1280,height:720,fps:30,bitrateKbps:4000},{width:960,height:540,fps:30,bitrateKbps:3000},{width:640,height:360,fps:24,bitrateKbps:1800}],vs=[{width:1080,height:1920,fps:30,bitrateKbps:10000},{width:720,height:1280,fps:30,bitrateKbps:4000},{width:540,height:960,fps:30,bitrateKbps:3000},{width:360,height:640,fps:24,bitrateKbps:1800}];setOut('horizontal',hs[level]);setOut('vertical',vs[level]);setReady(null)}
 function autoOptimize(){if(sessionActive)return;const outputs=cfg.mode==='dual'?2:1,per=cfg.uploadMbps>0?cfg.uploadMbps*.68/outputs:(cfg.qualityStrategy==='best'?12:cfg.qualityStrategy==='balanced'?6:cfg.qualityStrategy==='stable'?4.8:3.2);const level=cfg.safeMode?1:per>=10.8?0:per>=4?1:per>=2.8?2:3;applyPreset(level);setCfg({previewQuality:level>=2?'low':'medium'});setMessage(`Auto Optimize selected ${['Full 1080p','Stable 720p','Recovery 540p','Emergency 360p'][level]}.`);addEvent('success',`Auto Optimize selected level ${level}.`)}
 function applySafeMode(){setCfg({safeMode:true,qualityStrategy:'stable',previewQuality:'low',latencyPreference:'normal'});applyPreset(1);addEvent('warning','Maximum Stability mode enabled.')}
 async function analyzeNetwork(){const server=cfg.mode==='vertical'?cfg.vertical.server:cfg.horizontal.server;setNetwork({loading:true});const r=await window.arsal.networkAnalyze(server);setNetwork(r);addEvent(r.ok?'success':'error',r.ok?`YouTube server reachable · ${r.latencyMs} ms TCP latency.`:'Streaming server not reachable.')}
 function saveProfile(){const name=prompt('Profile name',profileName||'My Streaming Profile');if(!name)return;const c=structuredClone(cfg);c.horizontal.key='';c.vertical.key='';const next=[...profiles.filter(p=>p.name!==name),{name,cfg:c}];setProfiles(next);localStorage.setItem('arsalProfiles',JSON.stringify(next));setProfileName(name);addEvent('success',`Profile saved: ${name}`)}
 function loadProfile(name:string){setProfileName(name);const p=profiles.find(x=>x.name===name);if(!p)return;const c=p.cfg as AppConfig;useStore.setState({cfg:{...c,horizontal:{...c.horizontal,key:cfg.horizontal.key},vertical:{...c.vertical,key:cfg.vertical.key}}});setReady(null);addEvent('info',`Profile loaded: ${name}`)}
 async function exportDiagnostics(){const safe=structuredClone(cfg);safe.horizontal.key='';safe.vertical.key='';const p=await window.arsal.exportDiagnostics({generatedAt:new Date().toISOString(),app:'Arsal YouTube Live Ultra Pro Max',system,config:safe,playlist:playlist.map(({path,...x})=>({...x,path:'<local file>'})),horizontal:h,vertical:v,network,events});if(p)setMessage(`Diagnostics exported: ${p}`)}
 async function chooseOverlay(){const p=await window.arsal.chooseOverlay();if(p)setCfg({overlay:{...cfg.overlay,imagePath:p,imageEnabled:true}})}
 async function remux(){if(!cfg.recordDir)return;const n=await window.arsal.remux(cfg.recordDir);setMessage(`${n} recording(s) remuxed to MP4.`)}
 useEffect(()=>{if(!cfg.scheduler.enabled||!cfg.scheduler.autoStart)return;const t=setInterval(()=>{const d=new Date(),hm=`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`,day=d.getDay(),date=d.toISOString().slice(0,10);if(!cfg.scheduler.weekdays.includes(day))return;const startKey=`start-${date}-${hm}`,stopKey=`stop-${date}-${hm}`;if(cfg.scheduler.startTime&&hm===cfg.scheduler.startTime&&!sessionActive&&scheduleGuard!==startKey){setScheduleGuard(startKey);void startStream(true)}if(cfg.scheduler.stopTime&&hm===cfg.scheduler.stopTime&&sessionActive&&scheduleGuard!==stopKey){setScheduleGuard(stopKey);void window.arsal.stop().then(()=>{setSessionActive(false);addEvent('info','Scheduler stopped the stream.')})}},15000);return()=>clearInterval(t)},[cfg.scheduler,sessionActive,scheduleGuard,playlist,cfg]);
 const advice=critical?'Critical transport issue detected. Use Fix My Stream now.':poor?'Encoder/network is below real-time. Auto recovery will step down quality.':live?'Media is flowing in real-time. Keep YouTube Stream Health open for platform feedback.':connecting?'Connecting and validating real media flow…':'Ready for setup.';
 return <div className="appShell">
  <header className="topbar"><div className="brand"><div className="brandMark">AYL</div><div><h1>Arsal YouTube Live</h1><p>Ultra Pro Max Studio <span>v2.0</span></p></div></div><div className="topControls"><div className={`healthTop health-${health.toLowerCase()}`}><small>SESSION HEALTH</small><b>{health}</b></div><Badge state={live?'streaming':connecting?'connecting':ready?.ok?'ready':'offline'} label={live?'LIVE':connecting?'CONNECTING':ready?.ok?'READY':'OFFLINE'}/><div className="modeToggle"><button className={cfg.uiMode==='simple'?'active':''} onClick={()=>setCfg({uiMode:'simple'})}>Simple</button><button className={cfg.uiMode==='pro'?'active':''} onClick={()=>setCfg({uiMode:'pro'})}>Pro</button></div><label className="modeSelect"><span>STREAM MODE</span><select value={cfg.mode} disabled={sessionActive} onChange={e=>{setCfg({mode:e.target.value as StreamMode});setReady(null)}}><option value="dual">Dual 16:9 + 9:16</option><option value="horizontal">Horizontal only</option><option value="vertical">Vertical only</option></select></label></div></header>
  <div className="commandBar"><button className="cmd primary" onClick={addVideos} disabled={sessionActive}>＋ Add Playlist</button><button className="cmd" onClick={autoOptimize} disabled={sessionActive}>✦ Auto Optimize</button><button className={`cmd ${cfg.safeMode?'active':''}`} onClick={applySafeMode} disabled={sessionActive}>◈ Safe Mode</button><button className="cmd" onClick={analyzeNetwork}>⌁ Analyze Network</button><button className="cmd rescue" onClick={fixStream}>⚡ Fix My Stream</button>{profiles.length>0&&<select className="profileSelect" value={profileName} onChange={e=>loadProfile(e.target.value)}><option value="">Profiles…</option>{profiles.map(p=><option key={p.name}>{p.name}</option>)}</select>}<button className="cmd" onClick={saveProfile}>Save Profile</button></div>
  <div className="workflow"><span className={playlist.length?'done':''}><i>{playlist.length?'✓':'1'}</i><b>Media</b></span><em/><span className={keysReady?'done':''}><i>{keysReady?'✓':'2'}</i><b>Destinations</b></span><em/><span className={ready?.ok?'done':''}><i>{ready?.ok?'✓':'3'}</i><b>Pre-flight</b></span><em/><span className={live?'done':''}><i>{live?'✓':'4'}</i><b>Live ingest</b></span></div>
  <main className="studioGrid">
   <aside className="leftRail">
    <Section eyebrow="INPUT" title="Playlist Queue"><button className="bigAdd" onClick={addVideos} disabled={sessionActive}>＋ Add videos</button>{playlist.length?<><div className="playlistList">{playlist.map((m,i)=><div draggable={!sessionActive} onDragStart={()=>setDrag(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(drag!==null)reorderMedia(drag,i);setDrag(null)}} className={`playlistItem ${i===previewIndex?'selected':''}`} key={m.path} onClick={()=>setPreviewIndex(i)}><span className="drag">⋮⋮</span><Thumb media={m}/><span className="mediaInfo"><b>{m.name}</b><small>{m.width}×{m.height} · {m.fps.toFixed(1)}fps</small><small>{fmt(m.duration)} · {mb(m.size)} MB</small></span><button className="x" disabled={sessionActive} onClick={e=>{e.stopPropagation();removeMedia(i)}}>×</button></div>)}</div><button className="linkButton" disabled={sessionActive} onClick={clearPlaylist}>Clear playlist</button></>:<div className="emptyList"><b>Drop-in playlist workflow</b><span>Select one or many videos. Drag rows to reorder them.</span></div>}</Section>
    <Section eyebrow="PLAYBACK" title="Session"><Toggle title="Loop full playlist" sub="Last item returns to first" on={cfg.loop} set={x=>setCfg({loop:x})} disabled={sessionActive}/><Toggle title="Shuffle playlist" sub="Randomize order for this session" on={cfg.shuffle} set={x=>setCfg({shuffle:x})} disabled={sessionActive}/><Toggle title="Stream audio" sub="AAC stereo · 128 Kbps" on={cfg.audioEnabled} set={x=>setCfg({audioEnabled:x})} disabled={sessionActive}/><Toggle title="Adaptive Network" sub="Auto step-down when speed falls below real-time" on={cfg.adaptiveNetwork} set={x=>setCfg({adaptiveNetwork:x})} disabled={sessionActive}/><Toggle title="Auto quality recovery" sub="Try one step higher after 3 stable minutes" on={cfg.autoQualityRecovery} set={x=>setCfg({autoQualityRecovery:x})} disabled={sessionActive}/></Section>
   </aside>
   <section className="centerStage"><div className="stageHead"><span><small>LIVE STUDIO</small><h2>Output Preview</h2><p>Same playlist, independently framed for horizontal and vertical.</p></span><div className="stageChips"><span>{playlist.length} media</span><span>{cfg.safeMode?'Safe mode':cfg.qualityStrategy}</span><span>{cfg.encoder==='auto'?'Auto encoder':cfg.encoder.toUpperCase()}</span></div></div><div className="previews"><Preview kind="horizontal" index={previewIndex} setIndex={setPreviewIndex} stats={h}/><Preview kind="vertical" index={previewIndex} setIndex={setPreviewIndex} stats={v}/></div><div className="sceneDeck"><span><small>LIVE SCENES</small><b>{sessionActive?'Switching scenes briefly reconnects the encoder.':'Available once streaming starts.'}</b></span>{(['video','starting','brb','ending'] as SceneType[]).map(s=><button key={s} disabled={!sessionActive} className={scene===s?'active':''} onClick={()=>switchScene(s)}>{s==='video'?'▶ Video':s==='starting'?'◷ Starting Soon':s==='brb'?'Ⅱ BRB':'■ End Screen'}</button>)}</div>
    <div className="framing"><span><b>Vertical framing</b><small>Use Fill + crop for landscape sources.</small></span><label>X<input type="range" min="0" max="100" value={cfg.vertical.cropX} disabled={sessionActive} onChange={e=>setOut('vertical',{cropX:+e.target.value})}/></label><label>Y<input type="range" min="0" max="100" value={cfg.vertical.cropY} disabled={sessionActive} onChange={e=>setOut('vertical',{cropY:+e.target.value})}/></label><label>Zoom<input type="range" min="100" max="180" value={cfg.vertical.zoom} disabled={sessionActive} onChange={e=>setOut('vertical',{zoom:+e.target.value})}/></label></div>
   </section>
   <aside className="rightRail">
    <Section eyebrow="OUTPUT" title="Destinations">{hOn&&<KeyField kind="horizontal" stats={h}/>} {vOn&&<KeyField kind="vertical" stats={v}/>}<div className="templateRow"><button disabled={sessionActive} onClick={()=>{setOut('horizontal',{server:'rtmps://a.rtmps.youtube.com/live2'});setOut('vertical',{server:'rtmps://a.rtmps.youtube.com/live2'})}}>YouTube RTMPS</button><button onClick={analyzeNetwork}>Test server</button></div></Section>
    <Section eyebrow="SMART QUALITY" title="Auto Stability"><Field label="Quality strategy"><select disabled={sessionActive} value={cfg.qualityStrategy} onChange={e=>setCfg({qualityStrategy:e.target.value as QualityStrategy})}><option value="best">Best quality</option><option value="balanced">Balanced</option><option value="stable">Maximum stability</option><option value="weak">Weak internet</option></select></Field><Field label="Your upload speed (Mbps)" hint="Enter a recent speed-test upload result. Auto Optimize keeps headroom."><input type="number" min="0" step="0.5" disabled={sessionActive} value={cfg.uploadMbps||''} placeholder="e.g. 12" onChange={e=>setCfg({uploadMbps:+e.target.value||0})}/></Field><Field label="Encoder"><select disabled={sessionActive} value={cfg.encoder} onChange={e=>setCfg({encoder:e.target.value as Encoder})}><option value="auto">Auto GPU → CPU fallback</option><option value="nvenc">NVIDIA NVENC</option><option value="qsv">Intel Quick Sync</option><option value="amf">AMD AMF</option><option value="cpu">CPU x264</option></select></Field><div className="qualitySummary"><b>{(configuredKbps/1000).toFixed(1)} Mbps configured</b><span>{cfg.uploadMbps?`${Math.round(configuredKbps/10/cfg.uploadMbps)/10}% of entered upload`:'Set upload Mbps for smarter recommendations'}</span></div>{network&&<div className={`networkResult ${network.ok?'ok':'bad'}`}>{network.loading?'Testing…':network.ok?`Server reachable · ${network.latencyMs} ms · ${network.status}`:'Server unreachable / invalid URL'}</div>}</Section>
    <button className="preflightButton" onClick={preflight}>◇ Run pre-flight check</button>{ready&&<div className={`preflightBox ${ready.ok?'ok':'bad'}`}><b>{ready.ok?'✓ Ready locally':'✕ Fix before streaming'}</b>{ready.errors?.map((x:string)=><span key={x}>{x}</span>)}{ready.warnings?.slice(0,3).map((x:string)=><span className="warn" key={x}>⚠ {x}</span>)}</div>}
   </aside>
  </main>
  {cfg.uiMode==='pro'&&<section className="proWorkspace"><div className="tabs"><button className={tab==='health'?'active':''} onClick={()=>setTab('health')}>Health & Analytics</button><button className={tab==='tools'?'active':''} onClick={()=>setTab('tools')}>Pro Tools</button><button className={tab==='events'?'active':''} onClick={()=>setTab('events')}>Activity ({events.length})</button></div>{tab==='health'&&<div className="healthGrid"><StreamStat title="Horizontal 16:9" on={hOn} st={h} playlist={playlist}/><StreamStat title="Vertical 9:16" on={vOn} st={v} playlist={playlist}/><div className={`advisor advisor-${critical?'critical':poor?'poor':'good'}`}><small>SMART ADVISOR</small><h3>{advice}</h3><p>For highest resilience, use Normal latency in YouTube Studio and keep encoder speed at or above 1.0×.</p><button className="rescue" onClick={fixStream}>⚡ Fix My Stream</button></div></div>}
   {tab==='tools'&&<div className="toolGrid"><Section eyebrow="AUDIO" title="Processing"><Field label={`Volume ${cfg.audioVolume}%`}><input type="range" min="0" max="200" value={cfg.audioVolume} disabled={sessionActive} onChange={e=>setCfg({audioVolume:+e.target.value})}/></Field><Field label={`Gain ${cfg.audioProcessing.gainDb} dB`}><input type="range" min="-12" max="12" value={cfg.audioProcessing.gainDb} disabled={sessionActive} onChange={e=>setCfg({audioProcessing:{...cfg.audioProcessing,gainDb:+e.target.value}})}/></Field><Toggle title="Limiter" sub="Protect against clipping" on={cfg.audioProcessing.limiter} set={x=>setCfg({audioProcessing:{...cfg.audioProcessing,limiter:x}})} disabled={sessionActive}/><Toggle title="Compressor" sub="Even out loud/quiet audio" on={cfg.audioProcessing.compressor} set={x=>setCfg({audioProcessing:{...cfg.audioProcessing,compressor:x}})} disabled={sessionActive}/><Toggle title="Noise gate" sub="Reduce very low-level background noise" on={cfg.audioProcessing.noiseGate} set={x=>setCfg({audioProcessing:{...cfg.audioProcessing,noiseGate:x}})} disabled={sessionActive}/></Section>
    <Section eyebrow="OVERLAY" title="Branding"><Toggle title="Text overlay" on={cfg.overlay.enabled} set={x=>setCfg({overlay:{...cfg.overlay,enabled:x}})} disabled={sessionActive}/><Field label="Overlay text"><input disabled={sessionActive} value={cfg.overlay.text} onChange={e=>setCfg({overlay:{...cfg.overlay,text:e.target.value}})} placeholder="Channel name / LIVE"/></Field><Field label="Position"><select disabled={sessionActive} value={cfg.overlay.position} onChange={e=>setCfg({overlay:{...cfg.overlay,position:e.target.value as any}})}><option value="top-left">Top left</option><option value="top-right">Top right</option><option value="bottom-left">Bottom left</option><option value="bottom-right">Bottom right</option><option value="center">Center</option></select></Field><button disabled={sessionActive} onClick={chooseOverlay}>Choose logo / watermark</button>{cfg.overlay.imagePath&&<Toggle title="Image watermark" sub={cfg.overlay.imagePath.split(/[\\/]/).pop()} on={cfg.overlay.imageEnabled} set={x=>setCfg({overlay:{...cfg.overlay,imageEnabled:x}})} disabled={sessionActive}/>}</Section>
    <Section eyebrow="RECORDING" title="Local Backup"><Toggle title="Record local backup" sub="Segmented MKV for crash resistance" on={cfg.recordLocal} set={x=>setCfg({recordLocal:x})} disabled={sessionActive}/><Field label="Segment length"><select disabled={sessionActive} value={cfg.recordSegmentMinutes} onChange={e=>setCfg({recordSegmentMinutes:+e.target.value})}><option value={15}>15 minutes</option><option value={30}>30 minutes</option><option value={60}>60 minutes</option><option value={120}>2 hours</option></select></Field><button disabled={sessionActive} onClick={async()=>{const d=await window.arsal.chooseDir();if(d)setCfg({recordDir:d})}}>{cfg.recordDir?'Change folder':'Choose recording folder'}</button><Toggle title="Auto remux to MP4 after stop" on={cfg.autoRemux} set={x=>setCfg({autoRemux:x})} disabled={sessionActive}/><button disabled={!cfg.recordDir||sessionActive} onClick={remux}>Remux existing MKV → MP4</button></Section>
    <Section eyebrow="SCHEDULER" title="Automatic Session"><Toggle title="Scheduler enabled" on={cfg.scheduler.enabled} set={x=>setCfg({scheduler:{...cfg.scheduler,enabled:x}})}/><Toggle title="Allow automatic start" sub="Requires app open, valid playlist and key" on={cfg.scheduler.autoStart} set={x=>setCfg({scheduler:{...cfg.scheduler,autoStart:x}})}/><div className="timeGrid"><Field label="Start time"><input type="time" value={cfg.scheduler.startTime} onChange={e=>setCfg({scheduler:{...cfg.scheduler,startTime:e.target.value}})}/></Field><Field label="Stop time"><input type="time" value={cfg.scheduler.stopTime} onChange={e=>setCfg({scheduler:{...cfg.scheduler,stopTime:e.target.value}})}/></Field></div><DayPicker cfg={cfg} setCfg={setCfg}/></Section>
    <Section eyebrow="YOUTUBE" title="Playback Strategy"><Field label="Latency preference"><select value={cfg.latencyPreference} onChange={e=>setCfg({latencyPreference:e.target.value as LatencyPreference})}><option value="normal">Normal — most stable</option><option value="low">Low — balanced</option><option value="ultra">Ultra-low — least buffering headroom</option></select></Field><p className="hint">This is a planning preference. Set the actual latency in YouTube Live Control Room. Normal latency is best when upload is unstable.</p><Field label="Preview quality"><select value={cfg.previewQuality} onChange={e=>setCfg({previewQuality:e.target.value as any})}><option value="low">Low resource</option><option value="medium">Balanced</option><option value="high">High</option></select></Field><Toggle title="Remember keys securely" sub="Uses Windows encrypted storage" on={cfg.rememberKeys} set={x=>setCfg({rememberKeys:x})}/><button onClick={exportDiagnostics}>Export diagnostics</button></Section></div>}
   {tab==='events'&&<div className="eventLog">{events.length?events.slice().reverse().map((e,i)=><div className={`event e-${e.level}`} key={`${e.time}-${i}`}><time>{new Date(e.time).toLocaleTimeString()}</time><span>{e.message}</span></div>):<div className="emptyList">Session events will appear here.</div>}</div>}</section>}
  <footer className="controlDock"><div className="dockStatus"><i className={live?'live':''}/><span><b>{live?'Broadcasting live':connecting?'Connecting to YouTube':sessionActive?'Session active':'Ready to stream'}</b><small>{message}</small></span></div><div className="dockFacts"><span><small>MODE</small><b>{cfg.mode==='dual'?'DUAL':cfg.mode==='vertical'?'9:16':'16:9'}</b></span><span><small>PLAYLIST</small><b>{playlist.length}</b></span><span><small>OUTPUT</small><b>{(configuredKbps/1000).toFixed(1)} Mbps</b></span></div><div className="dockActions"><button onClick={preflight}>Pre-flight</button>{!sessionActive?<button className="go" onClick={()=>startStream(false)}>START LIVE</button>:<button className="stop" onClick={stopStream}>STOP LIVE</button>}</div></footer>
 </div>
}
