import path from 'path';
import fs from 'fs';
import { app } from 'electron';
import type { AppConfig,MediaInfo,OutputConfig,Encoder,SceneType,OutputKind,MultiDestination } from '../shared/types';
export function ffmpegPath(){return app.isPackaged?path.join(process.resourcesPath,'ffmpeg','ffmpeg.exe'):path.join(process.cwd(),'resources','ffmpeg',process.platform==='win32'?'ffmpeg.exe':'ffmpeg')}
export function ffprobePath(){return app.isPackaged?path.join(process.resourcesPath,'ffmpeg','ffprobe.exe'):path.join(process.cwd(),'resources','ffmpeg',process.platform==='win32'?'ffprobe.exe':'ffprobe')}
export function maskSecret(s:string){if(!s)return '';return s.length<9?'••••••••':`${s.slice(0,4)}••••••••${s.slice(-4)}`}
export function sanitizeArgs(args:string[]){return args.map(a=>a.replace(/(rtmps?:\/\/[^\s/|]+\/[^\s/|]+\/)[^\s|\]]+/gi,'$1<redacted>'))}
export function buildDestination(o:{server:string;key:string}){const server=o.server.trim().replace(/\/$/,'');const key=o.key.trim().replace(/^\//,'');return `${server}/${key}`}
export function outputKind(o:OutputConfig):OutputKind{return o.width>o.height?'horizontal':'vertical'}
export interface ResolvedDestination extends MultiDestination{url:string;primary:boolean}
export function destinationsForOutput(o:OutputConfig,cfg:AppConfig):ResolvedDestination[]{const kind=outputKind(o),all:MultiDestination[]=[{id:`primary-${kind}`,name:kind==='horizontal'?'Primary / Horizontal':'Vertical / Second',kind,enabled:true,server:o.server,key:o.key,priority:'primary',group:'Primary'},...cfg.multiDestinations.filter(d=>d.kind===kind&&d.enabled)];const seen=new Set<string>();return all.filter(d=>{if(!d.key.trim()||!/^rtmps?:\/\//i.test(d.server.trim()))return false;const url=buildDestination(d);if(seen.has(url))return false;seen.add(url);return true}).map(d=>({...d,url:buildDestination(d),primary:d.id.startsWith('primary-')}))}
export function buildFilter(o:OutputConfig):string{const W=o.width,H=o.height;if(o.fit==='stretch')return`scale=${W}:${H},setsar=1`;if(o.fit==='fit')return`scale=${W}:${H}:force_original_aspect_ratio=decrease,pad=${W}:${H}:(ow-iw)/2:(oh-ih)/2:black,setsar=1`;if(o.fit==='original')return`scale='min(iw,${W})':'min(ih,${H})':force_original_aspect_ratio=decrease,pad=${W}:${H}:(ow-iw)/2:(oh-ih)/2:black,setsar=1`;const z=Math.max(1,o.zoom/100),px=Math.max(0,Math.min(100,o.cropX))/100,py=Math.max(0,Math.min(100,o.cropY))/100;return`scale=iw*${z}:ih*${z},scale=${W}:${H}:force_original_aspect_ratio=increase,crop=${W}:${H}:(iw-${W})*${px}:(ih-${H})*${py},setsar=1`}
export function encoderArgs(enc:Encoder,b:number,fps:number,fastMode=false){const g=Math.max(24,Math.round(fps*2));if(enc==='nvenc')return['-c:v','h264_nvenc','-preset',fastMode?'p3':'p5','-rc','cbr','-b:v',`${b}k`,'-maxrate',`${b}k`,'-bufsize',`${b*2}k`,'-g',String(g),'-forced-idr','1'];if(enc==='qsv')return['-c:v','h264_qsv','-preset',fastMode?'veryfast':'medium','-b:v',`${b}k`,'-maxrate',`${b}k`,'-bufsize',`${b*2}k`,'-g',String(g)];if(enc==='amf')return['-c:v','h264_amf','-usage','ultralowlatency','-rc','cbr','-b:v',`${b}k`,'-maxrate',`${b}k`,'-bufsize',`${b*2}k`,'-g',String(g)];return['-c:v','libx264','-preset',fastMode?'superfast':'veryfast','-tune','zerolatency','-b:v',`${b}k`,'-maxrate',`${b}k`,'-bufsize',`${b*2}k`,'-g',String(g),'-keyint_min',String(g)]}
function escText(s:string){return(s||'').replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/:/g,'\\:').replace(/%/g,'\\%').replace(/\[/g,'\\[').replace(/\]/g,'\\]')}
function pos(p:AppConfig['overlay']['position'],W:number,H:number){const m=28;if(p==='top-left')return{x:String(m),y:String(m)};if(p==='top-right')return{x:`W-w-${m}`,y:String(m)};if(p==='bottom-left')return{x:String(m),y:`H-h-${m}`};if(p==='center')return{x:'(W-w)/2',y:'(H-h)/2'};return{x:`W-w-${m}`,y:`H-h-${m}`}}
function sceneText(cfg:AppConfig,scene:SceneType){return scene==='starting'?cfg.scenes.startingText:scene==='brb'?cfg.scenes.brbText:scene==='ending'?cfg.scenes.endingText:''}
function audioChain(cfg:AppConfig){const f=[`volume=${Math.pow(10,cfg.audioProcessing.gainDb/20)*(cfg.audioVolume/100)}`];if(cfg.audioProcessing.noiseGate)f.push('agate=threshold=0.02:ratio=3:attack=20:release=250');if(cfg.audioProcessing.compressor)f.push('acompressor=threshold=-18dB:ratio=3:attack=20:release=250');if(cfg.audioProcessing.limiter)f.push('alimiter=limit=0.95');return f.join(',')}
export interface RelayTarget{id:string;port:number}
export interface StreamBuildOptions{scene?:SceneType;fastMode?:boolean}
export function buildEncoderRelayArgs(playlist:MediaInfo[],concatFile:string|undefined,o:OutputConfig,cfg:AppConfig,encoder:Encoder,targets:RelayTarget[],opts:StreamBuildOptions={}){
 if(!playlist.length)throw new Error('Playlist is empty');if(!targets.length)throw new Error('No relay targets');const scene=opts.scene||'video',a=['-hide_banner','-loglevel','warning','-progress','pipe:1','-stats_period','1'];let next=0,sourceAudioIndex=-1,bgIndex=-1,overlayIndex=-1;
 if(scene==='video'){
  a.push('-re');if(cfg.loop)a.push('-stream_loop','-1');if(playlist.length>1&&concatFile)a.push('-f','concat','-safe','0','-i',concatFile);else a.push('-i',playlist[0].path);next=1;
  const hasSourceAudio=cfg.audioEnabled&&playlist.every(m=>m.hasAudio);if(hasSourceAudio)sourceAudioIndex=0;else{sourceAudioIndex=next++;a.push('-f','lavfi','-i','anullsrc=channel_layout=stereo:sample_rate=44100')}
 }else{a.push('-re','-f','lavfi','-i',`color=c=#07111f:s=${o.width}x${o.height}:r=${o.fps}`);next=1;sourceAudioIndex=next++;a.push('-f','lavfi','-i','anullsrc=channel_layout=stereo:sample_rate=44100')}
 if(cfg.backgroundAudio.enabled&&cfg.backgroundAudio.path&&fs.existsSync(cfg.backgroundAudio.path)){bgIndex=next++;a.push('-stream_loop','-1','-i',cfg.backgroundAudio.path)}
 if(cfg.overlay.imageEnabled&&cfg.overlay.imagePath&&fs.existsSync(cfg.overlay.imagePath)){overlayIndex=next++;a.push('-loop','1','-framerate','1','-i',cfg.overlay.imagePath)}
 const W=o.width,H=o.height,p=pos(cfg.overlay.position,W,H),parts:string[]=[];let base=buildFilter(o);
 if(scene!=='video'){const t=escText(sceneText(cfg,scene));base+=`,drawtext=text='${t}':fontcolor=white:fontsize=${Math.max(34,Math.round(H/16))}:x=(w-text_w)/2:y=(h-text_h)/2:box=1:boxcolor=black@0.42:boxborderw=26`}
 if(scene==='video'&&cfg.overlay.enabled&&cfg.overlay.text.trim()){const t=escText(cfg.overlay.text.trim());base+=`,drawtext=text='${t}':fontcolor=white:fontsize=${cfg.overlay.textSize}:x=${p.x}:y=${p.y}:box=1:boxcolor=black@0.35:boxborderw=10`}
 parts.push(`[0:v]${base}[base]`);
 if(overlayIndex>=0){parts.push(`[${overlayIndex}:v]format=rgba,colorchannelmixer=aa=${Math.max(.05,Math.min(1,cfg.overlay.opacity/100))},scale='min(iw,${Math.round(W*cfg.overlay.imageScale/100)})':-1[logo]`);parts.push(`[base][logo]overlay=${p.x}:${p.y}:format=auto[comp]`)}else parts.push('[base]null[comp]');
 if(cfg.recordLocal&&cfg.recordDir)parts.push('[comp]split=2[vnet][vrec]');else parts.push('[comp]null[vnet]');
 parts.push(`[${sourceAudioIndex}:a]${audioChain(cfg)}[voice]`);
 if(bgIndex>=0){parts.push(`[${bgIndex}:a]volume=${Math.max(0,Math.min(100,cfg.backgroundAudio.volume))/100}[music]`);if(cfg.backgroundAudio.ducking){parts.push('[music][voice]sidechaincompress=threshold=0.035:ratio=8:attack=20:release=450[ducked]');parts.push('[voice][ducked]amix=inputs=2:duration=first:dropout_transition=2[mix]')}else parts.push('[voice][music]amix=inputs=2:duration=first:dropout_transition=2[mix]')}else parts.push('[voice]anull[mix]');
 if(cfg.recordLocal&&cfg.recordDir)parts.push('[mix]asplit=2[anet][arec]');else parts.push('[mix]anull[anet]');
 a.push('-filter_complex',parts.join(';'));
 const addEncode=(v:string,au:string)=>a.push('-map',v,'-map',au,'-r',String(o.fps),'-fps_mode','cfr','-pix_fmt','yuv420p','-colorspace','bt709','-color_primaries','bt709','-color_trc','bt709',...encoderArgs(encoder,o.bitrateKbps,o.fps,!!opts.fastMode),'-c:a','aac','-b:a','128k','-ar','44100','-ac','2','-max_muxing_queue_size','4096');
 addEncode('[vnet]','[anet]');const tee=targets.map(t=>`[f=mpegts:onfail=ignore]udp://127.0.0.1:${t.port}?pkt_size=1316`).join('|');a.push('-f','tee',tee);
 if(cfg.recordLocal&&cfg.recordDir){addEncode('[vrec]','[arec]');const baseName=outputKind(o),pattern=path.join(cfg.recordDir,`${baseName}-%Y-%m-%d_%H-%M-%S.mkv`);a.push('-f','segment','-segment_time',String(Math.max(5,cfg.recordSegmentMinutes)*60),'-reset_timestamps','1','-strftime','1',pattern)}
 return a
}
export function buildRelayArgs(port:number,url:string){return['-hide_banner','-loglevel','warning','-progress','pipe:1','-stats_period','1','-fflags','+genpts+nobuffer','-i',`udp://127.0.0.1:${port}?fifo_size=1000000&overrun_nonfatal=1`,'-map','0:v:0','-map','0:a:0?','-c','copy','-flvflags','no_duration_filesize','-rw_timeout','15000000','-f','flv',url]}
export function buildStreamArgs(playlist:MediaInfo[],concatFile:string|undefined,o:OutputConfig,cfg:AppConfig,encoder:Encoder,opts:StreamBuildOptions={}){const d=destinationsForOutput(o,cfg);if(!d.length)throw new Error('No destination');return buildEncoderRelayArgs(playlist,concatFile,o,cfg,encoder,[{id:d[0].id,port:23999}],opts)}
export function ffmpegExists(){return fs.existsSync(ffmpegPath())&&fs.existsSync(ffprobePath())}
