import path from 'path';
import fs from 'fs';
import { app } from 'electron';
import type { AppConfig,MediaInfo,OutputConfig,Encoder } from '../shared/types';
export function ffmpegPath(){return app.isPackaged?path.join(process.resourcesPath,'ffmpeg','ffmpeg.exe'):path.join(process.cwd(),'resources','ffmpeg',process.platform==='win32'?'ffmpeg.exe':'ffmpeg')}
export function ffprobePath(){return app.isPackaged?path.join(process.resourcesPath,'ffmpeg','ffprobe.exe'):path.join(process.cwd(),'resources','ffmpeg',process.platform==='win32'?'ffprobe.exe':'ffprobe')}
export function maskSecret(s:string){if(!s)return '';return s.length<9?'••••••••':`${s.slice(0,4)}••••••••${s.slice(-4)}`}
export function sanitizeArgs(args:string[]){return args.map(a=>a.replace(/(rtmps?:\/\/[^\s/]+\/[^\s/]+\/)[^\s]+/gi,'$1<redacted>'))}
export function buildDestination(o:OutputConfig){const server=o.server.trim().replace(/\/$/,'');const key=o.key.trim().replace(/^\//,'');return `${server}/${key}`}
export function buildFilter(o:OutputConfig):string{const W=o.width,H=o.height;if(o.fit==='stretch')return `scale=${W}:${H},setsar=1`;if(o.fit==='fit')return `scale=${W}:${H}:force_original_aspect_ratio=decrease,pad=${W}:${H}:(ow-iw)/2:(oh-ih)/2:black,setsar=1`;if(o.fit==='original')return `scale='min(iw,${W})':'min(ih,${H})':force_original_aspect_ratio=decrease,pad=${W}:${H}:(ow-iw)/2:(oh-ih)/2:black,setsar=1`;const z=Math.max(1,o.zoom/100);const px=Math.max(0,Math.min(100,o.cropX))/100,py=Math.max(0,Math.min(100,o.cropY))/100;return `scale=iw*${z}:ih*${z},scale=${W}:${H}:force_original_aspect_ratio=increase,crop=${W}:${H}:(iw-${W})*${px}:(ih-${H})*${py},setsar=1`}
export function encoderArgs(enc:Encoder,b:number,fps:number){const g=fps*2;if(enc==='nvenc')return ['-c:v','h264_nvenc','-preset','p5','-rc','cbr','-b:v',`${b}k`,'-maxrate',`${b}k`,'-bufsize',`${b*2}k`,'-g',String(g),'-forced-idr','1'];if(enc==='qsv')return ['-c:v','h264_qsv','-b:v',`${b}k`,'-maxrate',`${b}k`,'-bufsize',`${b*2}k`,'-g',String(g)];if(enc==='amf')return ['-c:v','h264_amf','-rc','cbr','-b:v',`${b}k`,'-maxrate',`${b}k`,'-bufsize',`${b*2}k`,'-g',String(g)];return ['-c:v','libx264','-preset','veryfast','-tune','zerolatency','-b:v',`${b}k`,'-maxrate',`${b}k`,'-bufsize',`${b*2}k`,'-g',String(g),'-keyint_min',String(g)]}
export function buildStreamArgs(playlist:MediaInfo[],concatFile:string|undefined,o:OutputConfig,cfg:AppConfig,encoder:Encoder,effectiveBitrate=o.bitrateKbps){if(!playlist.length)throw new Error('Playlist is empty');const dest=buildDestination(o);const a=['-hide_banner','-loglevel','warning','-progress','pipe:1','-stats_period','1','-re'];if(cfg.loop)a.push('-stream_loop','-1');if(playlist.length>1&&concatFile)a.push('-f','concat','-safe','0','-i',concatFile);else a.push('-i',playlist[0].path);const useSourceAudio=cfg.audioEnabled&&playlist.every(m=>m.hasAudio);if(!useSourceAudio)a.push('-f','lavfi','-i','anullsrc=channel_layout=stereo:sample_rate=44100');const addOutput=(target:string,format:string,network:boolean)=>{a.push('-map','0:v:0');if(useSourceAudio)a.push('-map','0:a:0?');else a.push('-map','1:a:0');a.push('-vf',buildFilter(o),'-r',String(o.fps),'-fps_mode','cfr','-pix_fmt','yuv420p',...encoderArgs(encoder,effectiveBitrate,o.fps));if(useSourceAudio)a.push('-c:a','aac','-b:a','128k','-ar','44100','-ac','2','-af',`volume=${cfg.audioVolume/100}`);else a.push('-c:a','aac','-b:a','128k','-ar','44100','-ac','2');if(network)a.push('-rw_timeout','15000000','-flvflags','no_duration_filesize');a.push('-f',format,target)};addOutput(dest,'flv',true);if(cfg.recordLocal&&cfg.recordDir)addOutput(path.join(cfg.recordDir,`${o.width>o.height?'horizontal':'vertical'}-${Date.now()}.mkv`),'matroska',false);return a}
export function ffmpegExists(){return fs.existsSync(ffmpegPath())&&fs.existsSync(ffprobePath())}
