import { app,BrowserWindow,dialog,ipcMain,powerSaveBlocker } from 'electron';
import path from 'path';
import fs from 'fs';
import os from 'os';
import net from 'net';
import crypto from 'crypto';
import { spawn } from 'child_process';
import { destinationsForOutput,ffmpegExists,ffmpegPath,ffprobePath } from './ffmpeg';
import { loadConfig,saveConfig } from './settings';
import { StreamProcessManager } from './processManager';
import type { AppConfig,MediaInfo,Encoder,SceneType } from '../shared/types';
let win:BrowserWindow|null=null,mgr:StreamProcessManager|null=null,blocker:number|null=null,lastCfg:AppConfig|null=null;
const create=()=>{win=new BrowserWindow({width:1540,height:960,minWidth:1120,minHeight:700,backgroundColor:'#050b13',title:'Arsal YouTube Live Ultra Pro Max',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});const dev=process.env.VITE_DEV_SERVER_URL;if(dev)win.loadURL(dev);else win.loadFile(path.join(__dirname,'../../renderer/index.html'));win.on('close',(e)=>{if(mgr){e.preventDefault();dialog.showMessageBox(win!,{type:'warning',buttons:['Cancel Exit','Stop Stream and Exit'],defaultId:0,message:'A live stream session is active.'}).then(r=>{if(r.response===1){mgr?.stopAll();mgr=null;win?.destroy()}})}})};
function probe(p:string):Promise<MediaInfo>{return new Promise((res,rej)=>{const cp=spawn(ffprobePath(),['-v','error','-show_entries','format=duration,size','-show_entries','stream=index,codec_type,codec_name,width,height,r_frame_rate,channels','-of','json',p],{windowsHide:true});let out='',err='';cp.stdout.on('data',d=>out+=d);cp.stderr.on('data',d=>err+=d);cp.on('close',c=>{if(c!==0)return rej(new Error(err||'ffprobe failed'));try{const j=JSON.parse(out),v=j.streams.find((s:any)=>s.codec_type==='video');if(!v)return rej(new Error('No valid video stream found'));const a=j.streams.find((s:any)=>s.codec_type==='audio'),[n,d]=String(v.r_frame_rate||'30/1').split('/').map(Number);res({path:p,name:path.basename(p),size:+j.format.size||fs.statSync(p).size,duration:+j.format.duration||0,width:v.width,height:v.height,fps:d?n/d:n,videoCodec:v.codec_name||'unknown',audioCodec:a?.codec_name,audioChannels:a?.channels,hasAudio:!!a})}catch(e){rej(e)}})})}
const codecName=(e:Encoder)=>e==='nvenc'?'h264_nvenc':e==='qsv'?'h264_qsv':e==='amf'?'h264_amf':'libx264';
function testEncoder(enc:Encoder):Promise<boolean>{if(enc==='cpu')return Promise.resolve(true);return new Promise(r=>{const started=Date.now(),cp=spawn(ffmpegPath(),['-hide_banner','-loglevel','error','-f','lavfi','-i','color=c=black:s=720x1280:r=30','-frames:v','45','-an','-c:v',codecName(enc),'-f','null','-'],{windowsHide:true});let settled=false;const done=(ok:boolean)=>{if(settled)return;settled=true;r(ok)};const timer=setTimeout(()=>{try{cp.kill()}catch{}done(false)},8000);cp.on('error',()=>{clearTimeout(timer);done(false)});cp.on('exit',c=>{clearTimeout(timer);done(c===0&&Date.now()-started<8000)})})}
async function detectEncoder(pref:Encoder){if(pref!=='auto'){if(await testEncoder(pref))return{encoder:pref};return{encoder:'cpu' as Encoder,fallbackFrom:pref}}for(const e of ['nvenc','qsv','amf'] as Encoder[])if(await testEncoder(e))return{encoder:e};return{encoder:'cpu' as Encoder}}
function analyzeServer(server:string){return new Promise<any>(resolve=>{try{const u=new URL(server),host=u.hostname,port=Number(u.port)||(u.protocol==='rtmps:'?443:1935),samples:number[]=[];let n=0;const next=()=>{if(n++>=3){const avg=samples.length?Math.round(samples.reduce((a,b)=>a+b,0)/samples.length):0;return resolve({ok:samples.length>0,host,port,latencyMs:avg,samples,status:!samples.length?'unreachable':avg<80?'excellent':avg<160?'good':avg<300?'fair':'poor'})}const t=Date.now(),s=net.createConnection({host,port});const finish=(ok:boolean)=>{s.destroy();if(ok)samples.push(Date.now()-t);setTimeout(next,120)};s.setTimeout(3500);s.once('connect',()=>finish(true));s.once('timeout',()=>finish(false));s.once('error',()=>finish(false))};next()}catch(e:any){resolve({ok:false,error:e.message,status:'invalid'})}})}
function thumbnail(p:string):Promise<string>{return new Promise(res=>{const id=crypto.createHash('sha1').update(p).digest('hex').slice(0,14),out=path.join(app.getPath('temp'),`arsal-thumb-${id}.jpg`);if(fs.existsSync(out))return res(out);const cp=spawn(ffmpegPath(),['-hide_banner','-loglevel','error','-ss','1','-i',p,'-frames:v','1','-vf','scale=320:-2','-q:v','4','-y',out],{windowsHide:true});cp.on('exit',c=>res(c===0?out:''));cp.on('error',()=>res(''))})}
function remuxFolder(dir:string):Promise<number>{return new Promise(async resolve=>{try{const files=fs.readdirSync(dir).filter(x=>x.toLowerCase().endsWith('.mkv'));let done=0;for(const f of files){const src=path.join(dir,f),dst=path.join(dir,f.replace(/\.mkv$/i,'.mp4'));if(fs.existsSync(dst))continue;await new Promise<void>(r=>{const cp=spawn(ffmpegPath(),['-hide_banner','-loglevel','error','-i',src,'-c','copy','-movflags','+faststart','-y',dst],{windowsHide:true});cp.on('exit',c=>{if(c===0)done++;r()});cp.on('error',()=>r())})}resolve(done)}catch{resolve(0)}})}
app.whenReady().then(()=>{
 create();
 ipcMain.handle('video:openMany',async()=>{const r=await dialog.showOpenDialog(win!,{properties:['openFile','multiSelections'],filters:[{name:'Video',extensions:['mp4','mov','mkv','avi','webm','m4v','ts']}]});if(r.canceled)return[];const items:MediaInfo[]=[];for(const p of r.filePaths)try{items.push(await probe(p))}catch{}return items});
 ipcMain.handle('video:thumbnail',(_:any,p:string)=>thumbnail(p));
 ipcMain.handle('overlay:choose',async()=>{const r=await dialog.showOpenDialog(win!,{properties:['openFile'],filters:[{name:'Image',extensions:['png','jpg','jpeg','webp']}]});return r.canceled?'':r.filePaths[0]});
 ipcMain.handle('dir:choose',async()=>{const r=await dialog.showOpenDialog(win!,{properties:['openDirectory']});return r.canceled?'':r.filePaths[0]});
 ipcMain.handle('config:load',()=>loadConfig());ipcMain.handle('config:save',(_:any,c:AppConfig)=>{saveConfig(c);return true});
 ipcMain.handle('network:analyze',(_:any,server:string)=>analyzeServer(server));
 ipcMain.handle('stream:preflight',async(_:any,p:{playlist:MediaInfo[],cfg:AppConfig})=>{
  const errors:string[]=[],warnings:string[]=[],list=p.playlist||[];if(!list.length)errors.push('Add at least one video to the playlist.');for(const m of list)if(!fs.existsSync(m.path))errors.push(`Missing file: ${m.name}`);if(!ffmpegExists())errors.push('Bundled FFmpeg/FFprobe not found.');
  const hNeeded=p.cfg.mode!=='vertical',vNeeded=p.cfg.mode!=='horizontal';
  for(const d of p.cfg.multiDestinations.filter(d=>d.enabled)){if(!d.name.trim())errors.push('Every enabled multi-channel destination needs a channel name.');if(!d.key.trim())errors.push(`${d.name||'Multi-channel destination'} stream key is missing.`);if(!/^rtmps?:\/\//i.test(d.server.trim()))errors.push(`${d.name||'Multi-channel destination'} server must start with rtmp:// or rtmps://.`)}
  const hD=hNeeded?destinationsForOutput(p.cfg.horizontal,p.cfg):[],vD=vNeeded?destinationsForOutput(p.cfg.vertical,p.cfg):[];
  if(hNeeded&&!hD.length)errors.push('Horizontal output has no enabled destination with a valid stream key.');if(vNeeded&&!vD.length)errors.push('Vertical output has no enabled destination with a valid stream key.');
  const hEach=p.cfg.horizontal.bitrateKbps+(p.cfg.audioEnabled?128:0),vEach=p.cfg.vertical.bitrateKbps+(p.cfg.audioEnabled?128:0),total=hEach*hD.length+vEach*vD.length;
  if(p.cfg.uploadMbps>0&&total/1000>p.cfg.uploadMbps*.72)warnings.push(`Multi-channel output needs about ${(total/1000).toFixed(1)} Mbps before overhead, which is high for your ${p.cfg.uploadMbps.toFixed(1)} Mbps upload setting. Use Auto Optimize / Safe Mode or reduce channels.`);
  if(hD.length+vD.length>4)warnings.push(`${hD.length+vD.length} simultaneous destinations are enabled. Encoding is shared, but upload bandwidth is multiplied per channel.`);
  if(p.cfg.latencyPreference==='ultra')warnings.push('Ultra-low latency gives viewers less buffer and is less tolerant of weak internet. Normal latency is better for stability.');if(p.cfg.recordLocal)warnings.push('Local recording adds extra encode/load. If encoder speed drops below 1.0×, disable recording or use Safe Mode.');if(new Set(list.map(m=>m.videoCodec)).size>1)warnings.push('Playlist contains mixed video codecs. Matching formats are more reliable for gap-free looping.');warnings.push('Pre-flight validates local settings. LIVE status is shown only after FFmpeg reports real output progress.');
  return{ok:!errors.length,errors,warnings,ffmpeg:ffmpegExists(),count:list.length,totalMbps:total/1000,destinations:{horizontal:hD.length,vertical:vD.length,total:hD.length+vD.length}}
 });
 ipcMain.handle('stream:start',async(_:any,p:{playlist:MediaInfo[],cfg:AppConfig})=>{if(mgr)return{ok:false,error:'A stream session is already active.'};if(!p.playlist?.length)return{ok:false,error:'Playlist is empty.'};const enc=await detectEncoder(p.cfg.encoder);lastCfg=p.cfg;mgr=new StreamProcessManager(p.playlist,p.cfg,enc.encoder);mgr.on('stats',x=>win?.webContents.send('stream:stats',x));mgr.on('event',x=>win?.webContents.send('stream:event',x));if(p.cfg.mode!=='vertical')mgr.start('horizontal',p.cfg.horizontal);if(p.cfg.mode!=='horizontal')mgr.start('vertical',p.cfg.vertical);blocker=powerSaveBlocker.start('prevent-display-sleep');saveConfig(p.cfg);return{ok:true,encoder:enc.encoder,fallbackFrom:enc.fallbackFrom}});
 ipcMain.handle('stream:fix',()=>{mgr?.fixMyStream();return!!mgr});ipcMain.handle('scene:switch',(_:any,scene:SceneType)=>{mgr?.switchScene(scene);return!!mgr});
 ipcMain.handle('stream:stop',async()=>{mgr?.stopAll();mgr=null;if(blocker!==null&&powerSaveBlocker.isStarted(blocker))powerSaveBlocker.stop(blocker);blocker=null;if(lastCfg?.autoRemux&&lastCfg.recordLocal&&lastCfg.recordDir)setTimeout(()=>void remuxFolder(lastCfg!.recordDir),5000);return true});
 ipcMain.handle('recordings:remux',(_:any,dir:string)=>remuxFolder(dir));
 ipcMain.handle('diagnostics:export',async(_:any,data:any)=>{const r=await dialog.showSaveDialog(win!,{defaultPath:`Arsal-Live-Diagnostics-${new Date().toISOString().replace(/[:.]/g,'-')}.json`,filters:[{name:'JSON',extensions:['json']}]});if(r.canceled||!r.filePath)return'';fs.writeFileSync(r.filePath,JSON.stringify(data,null,2));return r.filePath});
 ipcMain.handle('system:info',()=>({platform:process.platform,release:os.release(),cpu:os.cpus()[0]?.model,cpuCores:os.cpus().length,ramGB:Math.round(os.totalmem()/1024/1024/1024),freeRamGB:Math.round(os.freemem()/1024/1024/1024*10)/10,ffmpeg:ffmpegExists(),version:app.getVersion()}));
});
app.on('window-all-closed',()=>{mgr?.stopAll();if(process.platform!=='darwin')app.quit()});
