import { ChildProcessWithoutNullStreams,spawn } from 'child_process';
import { EventEmitter } from 'events';
import fs from 'fs';
import os from 'os';
import path from 'path';
import type { AppConfig,MediaInfo,OutputConfig,StreamStats,Encoder,SceneType,SessionEvent } from '../shared/types';
import { buildStreamArgs,destinationsForOutput,ffmpegPath,sanitizeArgs } from './ffmpeg';
import { effectiveProfile,initialAdaptiveLevel,transportHealth } from '../shared/adaptive';
type K='horizontal'|'vertical';
const blank=():StreamStats=>({state:'offline',health:'idle',fps:0,bitrateKbps:0,speed:'0x',frames:0,elapsed:0,reconnects:0,playlistIndex:0,adaptiveLevel:0,currentScene:'video',destinationCount:0});
const parseClock=(x:string)=>{const m=x.match(/(\d+):(\d+):(\d+(?:\.\d+)?)/);return m?(+m[1])*3600+(+m[2])*60+(+m[3]):0};
const speedNumber=(x:string)=>parseFloat(String(x).replace('x',''))||0;
export class StreamProcessManager extends EventEmitter{
 private p=new Map<K,ChildProcessWithoutNullStreams>();private stopSet=new Set<K>();private lastMetricEmit=new Map<K,number>();private reconnectTimers=new Map<K,NodeJS.Timeout>();private tempDir?:string;private concatFile?:string;private outputCfg=new Map<K,OutputConfig>();private levels=new Map<K,number>();private slowTicks=new Map<K,number>();private healthySince=new Map<K,number>();private lastAdapt=new Map<K,number>();private restartIntent=new Map<K,string>();private scene:SceneType='video';private finishedNormally=new Set<K>();
 stats:Record<K,StreamStats>={horizontal:blank(),vertical:blank()};private sessionPlaylist:MediaInfo[];
 constructor(private playlist:MediaInfo[],private cfg:AppConfig,private encoder:Encoder){super();this.sessionPlaylist=cfg.shuffle&&playlist.length>1?[...playlist].sort(()=>Math.random()-.5):[...playlist];if(this.sessionPlaylist.length>1){this.tempDir=fs.mkdtempSync(path.join(os.tmpdir(),'arsal-live-'));this.concatFile=path.join(this.tempDir,'playlist.ffconcat');const lines=['ffconcat version 1.0',...this.sessionPlaylist.map(m=>`file '${m.path.replace(/\\/g,'/').replace(/'/g,"\\'")}'`)];fs.writeFileSync(this.concatFile,lines.join('\n'),'utf8')}}
 private event(level:SessionEvent['level'],message:string){this.emit('event',{time:Date.now(),level,message} satisfies SessionEvent)}
 start(k:K,o:OutputConfig){if(this.p.has(k))return;this.outputCfg.set(k,o);this.stopSet.delete(k);this.levels.set(k,initialAdaptiveLevel(this.cfg.qualityStrategy,this.cfg.safeMode));this.launch(k)}
 private playlistIndex(elapsed:number){const total=this.sessionPlaylist.reduce((s,m)=>s+Math.max(.01,m.duration),0);if(!total)return 0;let t=this.cfg.loop?elapsed%total:Math.min(elapsed,total-.001);for(let i=0;i<this.sessionPlaylist.length;i++){if(t<this.sessionPlaylist[i].duration)return i;t-=this.sessionPlaylist[i].duration}return Math.max(0,this.sessionPlaylist.length-1)}
 private friendly(line:string){const clean=sanitizeArgs([line])[0];if(/nvenc|qsv|amf/i.test(clean)&&/error|failed|device|driver|initialize/i.test(clean))return'Hardware encoder failed to initialize.';if(/tls|ssl/i.test(clean)&&/error|failed/i.test(clean))return'Secure RTMPS/TLS connection failed.';if(/connection refused|failed to connect|cannot open connection/i.test(clean))return'Could not connect to one or more streaming destinations.';if(/broken pipe|connection reset/i.test(clean))return'A streaming destination connection was interrupted.';if(/timed out|timeout/i.test(clean))return'Streaming server connection timed out.';if(/server error|i\/o error|input\/output error/i.test(clean))return'One or more destinations rejected or closed the connection. Check server URL and stream key.';if(/invalid data|could not find codec parameters/i.test(clean))return'A playlist item is not compatible with this session.';return undefined}
 private profile(k:K){const base=this.outputCfg.get(k)!;return effectiveProfile(k,base,this.levels.get(k)||0,this.cfg.qualityStrategy,this.cfg.safeMode)}
 private launch(k:K){
  const base=this.outputCfg.get(k);if(!base||this.stopSet.has(k))return;const prof=this.profile(k),effective:OutputConfig={...base,width:prof.width,height:prof.height,fps:prof.fps,bitrateKbps:prof.bitrateKbps},destCount=destinationsForOutput(effective,this.cfg).length;const quality=prof.level===0?'full':prof.level===1?'adaptive':prof.level===2?'recovery':'emergency';
  this.finishedNormally.delete(k);this.set(k,{state:'connecting',health:'idle',targetBitrateKbps:prof.bitrateKbps,networkQuality:quality,adaptiveLevel:prof.level,effectiveWidth:prof.width,effectiveHeight:prof.height,effectiveFps:prof.fps,profileLabel:prof.label,currentScene:this.scene,destinationCount:destCount,lastError:undefined,lastWarning:undefined},true);
  let args:string[];try{args=buildStreamArgs(this.sessionPlaylist,this.concatFile,effective,this.cfg,this.encoder,{scene:this.scene,fastMode:prof.level>0||this.cfg.safeMode})}catch(e:any){this.set(k,{state:'error',health:'critical',lastError:e.message},true);this.event('error',`${k}: ${e.message}`);return}
  const cp=spawn(ffmpegPath(),args,{windowsHide:true});this.p.set(k,cp);this.event('info',`${k==='horizontal'?'Horizontal':'Vertical'} connecting to ${destCount} destination${destCount===1?'':'s'} · ${prof.label} · ${(prof.bitrateKbps/1000).toFixed(1)} Mbps each`);
  let stdout='',progress:Record<string,string>={},lastFriendly='';
  cp.stdout.setEncoding('utf8');cp.stdout.on('data',(chunk:string)=>{stdout+=chunk;let nl=stdout.indexOf('\n');while(nl>=0){const line=stdout.slice(0,nl).trim();stdout=stdout.slice(nl+1);const eq=line.indexOf('=');if(eq>0)progress[line.slice(0,eq)]=line.slice(eq+1);if(line.startsWith('progress=')){const frame=Number(progress.frame||0),fps=Number(progress.fps||0),br=parseFloat(progress.bitrate||'0')||0,speed=progress.speed||'0x',sv=speedNumber(speed),elapsed=parseClock(progress.out_time||'0:00:00'),drop=Number(progress.drop_frames||0),bytes=Number(progress.total_size||0);const st=this.stats[k],health=transportHealth(frame>0&&elapsed>0?'streaming':st.state,sv,st.reconnects||0);const patch:Partial<StreamStats>={frames:frame,fps,bitrateKbps:br,speed,elapsed,droppedFrames:drop,sessionBytes:bytes,playlistIndex:this.playlistIndex(elapsed),targetBitrateKbps:prof.bitrateKbps,networkQuality:quality,adaptiveLevel:prof.level,effectiveWidth:prof.width,effectiveHeight:prof.height,effectiveFps:prof.fps,profileLabel:prof.label,currentScene:this.scene,destinationCount:destCount,health};if(frame>0&&elapsed>0){if(st.state!=='streaming')this.event('success',`${k==='horizontal'?'Horizontal':'Vertical'} media is flowing to ${destCount} configured destination${destCount===1?'':'s'}.`);patch.state='streaming';patch.connectedAt=st.connectedAt||Date.now();patch.lastError=undefined}this.set(k,patch,line==='progress=end');if(line==='progress=end')this.finishedNormally.add(k);this.watchPerformance(k,sv);progress={}}nl=stdout.indexOf('\n')}});
  cp.stderr.setEncoding('utf8');cp.stderr.on('data',(s:string)=>{for(const raw of s.split(/\r?\n/)){const f=this.friendly(raw);if(f&&f!==lastFriendly){lastFriendly=f;this.set(k,{lastError:f},true);this.event('warning',`${k}: ${f}`)}}});
  cp.on('error',e=>{this.set(k,{state:'error',health:'critical',lastError:e.message},true);this.event('error',`${k}: ${e.message}`)});
  cp.on('exit',(code)=>{this.p.delete(k);if(this.stopSet.has(k)){this.set(k,{state:'offline',health:'idle'},true);return}const intent=this.restartIntent.get(k);if(intent){this.restartIntent.delete(k);this.event('info',`${k}: ${intent}`);setTimeout(()=>this.launch(k),350);return}if(this.finishedNormally.has(k)&&!this.cfg.loop){this.set(k,{state:'offline',health:'idle'},true);this.event('success',`${k}: playlist completed.`);return}const reason=lastFriendly||`Encoder exited${code===null?'':` with code ${code}`}.`;if(this.cfg.autoReconnect){const n=(this.stats[k].reconnects||0)+1;this.stats[k].reconnects=n;if(this.cfg.adaptiveNetwork&&n>1)this.levels.set(k,Math.min(3,(this.levels.get(k)||0)+1));this.set(k,{state:'reconnecting',health:'poor',reconnects:n,lastError:reason},true);const delays=[1500,3000,6000,10000,15000,30000],t=setTimeout(()=>{if(!this.stopSet.has(k))this.launch(k)},delays[Math.min(n-1,delays.length-1)]);this.reconnectTimers.set(k,t)}else this.set(k,{state:'error',health:'critical',lastError:reason},true)});
 }
 private watchPerformance(k:K,speed:number){if(this.scene!=='video'||!this.cfg.adaptiveNetwork||this.stats[k].state!=='streaming')return;const now=Date.now(),level=this.levels.get(k)||0;if(speed>0&&speed<.92){this.healthySince.delete(k);const ticks=(this.slowTicks.get(k)||0)+1;this.slowTicks.set(k,ticks);this.set(k,{lastWarning:`Encoder is below real-time (${speed.toFixed(2)}×). Auto Optimize is monitoring.`},false);if(ticks>=5&&level<3&&now-(this.lastAdapt.get(k)||0)>12000){this.slowTicks.set(k,0);this.lastAdapt.set(k,now);this.levels.set(k,level+1);this.restart(k,'Performance recovery: stepping down quality because encoder speed stayed below real-time.')}}else if(speed>=.98){this.slowTicks.set(k,0);if(!this.healthySince.has(k))this.healthySince.set(k,now);const since=this.healthySince.get(k)||now;if(this.cfg.autoQualityRecovery&&level>initialAdaptiveLevel(this.cfg.qualityStrategy,this.cfg.safeMode)&&now-since>180000&&now-(this.lastAdapt.get(k)||0)>180000){this.lastAdapt.set(k,now);this.healthySince.set(k,now);this.levels.set(k,level-1);this.restart(k,'Connection stable for 3 minutes: testing one quality step higher.')}}}
 private restart(k:K,reason:string){const cp=this.p.get(k);if(!cp){setTimeout(()=>this.launch(k),250);return}this.restartIntent.set(k,reason);this.set(k,{state:'reconnecting',health:'fair',lastWarning:reason},true);try{if(!cp.stdin.destroyed)cp.stdin.write('q\n')}catch{}setTimeout(()=>{if(!cp.killed)cp.kill()},2500)}
 fixMyStream(){for(const k of ['horizontal','vertical'] as K[]){if(!this.outputCfg.has(k))continue;const level=this.levels.get(k)||0;if(level<3)this.levels.set(k,level+1);this.restart(k,'Fix My Stream applied a safer quality profile.')}this.event('warning','Fix My Stream applied automatic stability settings.')}
 switchScene(scene:SceneType){if(this.scene===scene)return;this.scene=scene;for(const k of ['horizontal','vertical'] as K[])if(this.outputCfg.has(k))this.restart(k,`Switching scene to ${scene}.`);this.event('info',`Scene switched to ${scene}.`)}
 private set(k:K,patch:Partial<StreamStats>,force=false){this.stats[k]={...this.stats[k],...patch};const now=Date.now(),last=this.lastMetricEmit.get(k)||0;if(!force&&now-last<500)return;this.lastMetricEmit.set(k,now);this.emit('stats',{key:k,stats:this.stats[k]})}
 stop(k:K){this.stopSet.add(k);const t=this.reconnectTimers.get(k);if(t)clearTimeout(t);const cp=this.p.get(k);if(!cp){this.set(k,{state:'offline',health:'idle'},true);return}this.set(k,{state:'stopping'},true);try{if(!cp.stdin.destroyed)cp.stdin.write('q\n')}catch{}setTimeout(()=>{if(!cp.killed)cp.kill()},4000)}
 stopAll(){this.stop('horizontal');this.stop('vertical');this.event('info','Streaming session stopped.');setTimeout(()=>{if(this.tempDir)try{fs.rmSync(this.tempDir,{recursive:true,force:true})}catch{}},5000)}
}
