import http from 'http';
import os from 'os';
import type { RemoteControlConfig,SceneType } from '../shared/types';
export interface RemoteActions{status:()=>any;fix:()=>void;scene:(s:SceneType)=>void;retryFailed:()=>number;stop:()=>void}
function html(token:string){return`<!doctype html><html><head><meta name=viewport content="width=device-width,initial-scale=1"><title>Arsal Live Remote</title><style>body{font-family:system-ui;background:#07101b;color:#eef5ff;margin:0;padding:20px}h2{margin:0 0 6px}.sub{color:#8da2bb;margin-bottom:20px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}button{padding:16px;border:1px solid #28415f;border-radius:12px;background:#10233a;color:white;font-weight:700}.danger{background:#742b36}.fix{background:#245fc4}.status{margin-top:16px;padding:14px;background:#0d1a29;border-radius:12px;white-space:pre-wrap;font-size:12px}</style></head><body><h2>Arsal YouTube Live</h2><div class=sub>Remote Operator Console</div><div class=grid><button onclick="act('video')">▶ VIDEO</button><button onclick="act('starting')">◷ STARTING</button><button onclick="act('brb')">Ⅱ BRB</button><button onclick="act('ending')">■ END SCREEN</button><button class=fix onclick="post('fix')">⚡ FIX STREAMS</button><button onclick="post('retryFailed')">↻ RETRY FAILED</button><button class=danger onclick="if(confirm('Stop all streams?'))post('stop')">STOP ALL</button><button onclick=refresh()>REFRESH</button></div><div id=s class=status>Loading…</div><script>const token=${JSON.stringify(token)};async function post(action,extra={}){await fetch('/action?token='+encodeURIComponent(token),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...extra})});setTimeout(refresh,300)}function act(scene){post('scene',{scene})}async function refresh(){try{const r=await fetch('/status?token='+encodeURIComponent(token));document.getElementById('s').textContent=JSON.stringify(await r.json(),null,2)}catch(e){document.getElementById('s').textContent=String(e)}}refresh();setInterval(refresh,2500)</script></body></html>`}
export class RemoteServer{
 private server:http.Server|null=null;private current='';private actions:RemoteActions|null=null;
 configure(cfg:RemoteControlConfig,actions:RemoteActions){this.actions=actions;const signature=JSON.stringify({enabled:cfg.enabled,lan:cfg.lan,port:cfg.port,token:cfg.token});if(signature===this.current)return;this.stop();this.current=signature;if(!cfg.enabled||!cfg.token)return;const authorized=(req:http.IncomingMessage)=>{try{const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);return u.searchParams.get('token')===cfg.token||req.headers['x-arsal-token']===cfg.token}catch{return false}};this.server=http.createServer((req,res)=>{res.setHeader('Cache-Control','no-store');if(!authorized(req)){res.writeHead(401,{'content-type':'application/json'});res.end(JSON.stringify({error:'Unauthorized'}));return}const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&u.pathname==='/'){res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(html(cfg.token));return}if(req.method==='GET'&&u.pathname==='/status'){res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(this.actions?.status()||{}));return}if(req.method==='POST'&&u.pathname==='/action'){let body='';req.on('data',d=>{body+=d;if(body.length>32768)req.destroy()});req.on('end',()=>{try{const x=JSON.parse(body||'{}'),a=String(x.action||'');if(a==='fix')this.actions?.fix();else if(a==='scene'&&['video','starting','brb','ending'].includes(x.scene))this.actions?.scene(x.scene);else if(a==='retryFailed')this.actions?.retryFailed();else if(a==='stop')this.actions?.stop();else throw new Error('Unsupported action');res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({ok:true}))}catch(e:any){res.writeHead(400,{'content-type':'application/json'});res.end(JSON.stringify({ok:false,error:e.message}))}});return}res.writeHead(404);res.end()});const host=cfg.lan?'0.0.0.0':'127.0.0.1';this.server.listen(cfg.port,host);this.server.unref()}
 stop(){try{this.server?.close()}catch{}this.server=null}
 info(cfg:RemoteControlConfig){const ips=Object.values(os.networkInterfaces()).flat().filter((x:any)=>x&&x.family==='IPv4'&&!x.internal).map((x:any)=>x.address);return{enabled:!!this.server,port:cfg.port,lan:cfg.lan,localUrl:`http://127.0.0.1:${cfg.port}/?token=${encodeURIComponent(cfg.token)}`,lanUrls:cfg.lan?ips.map(ip=>`http://${ip}:${cfg.port}/?token=${encodeURIComponent(cfg.token)}`):[]}}
}
